### ISSUE TITLE
Rebrand for white-label

### ISSUE THREAD

**Issue by isysd** [deginner/DeShifty#1]
Basically remove Shape-shift branding and replace with generic terminology. Will be a generic conversion button that should be able work with a variety of backend servers. One added bit of functionality is to also make the "shift to" or output currency configurable by letting the user insert the "destination" address and sensing it's type.

So the new options will be:

Input currency:
 + Bitcoin
 + Dash
 + US Dollars

Destination: (required address field)
Output currency: (sensed and filled in based on destination address type)

Still gather the required amount and optional return and email address fields. Leave deposit limit and exchange rate to be filled in by #2.

References to Shapeshift i.e. "powered by" should be replaced

**Comment by luisvillara** [comment]
Hi @isysd how are you doing?

I'm working on this, but, I have some questions about how this issue should fix (I attached a screenshot).
So, the questions are:

1. I don't know where put the output currency? See the screenshot and let me know how can I help you.
2. I have to test the API? And make sure that all the scripts work?

<img width="682" alt="screen shot 2016-04-13 at 5 34 52 pm" src="https://cloud.githubusercontent.com/assets/2540621/14511074/d668f80e-019e-11e6-8cfa-6730c68b9270.png">
*This is an advance*

PD: Sorry for my english

Regards,
Luis

**Comment by isysd** [comment]
Hi @luisvillara! Good to work with you again.

1. The "Output currency" shown above is hard coded to Bitcoin, and is shown in the left as "Shift To." In my opinion, it makes sense to move it to the right. In is left, out is right. Also, there should be a text field for the user to input an address. Based on this address, the currency is known.

For example, if the address starts with 1, or 3, it might be a bitcoin address. If it starts with X or Y, Dash.

2. No. The API isn't ready yet, so please just prepare all of the parameters as if you would send them to Shapeshift, then print to console. The API is part of task #2.

**Comment by isysd** [comment]
One more thing, please change the background and color scheme... they're Shapeshift colors. Perhaps something neutral, based on white or grey?

**Comment by luisvillara** [comment]
Hi @isysd, please let me know if this design works for you. I put the "Shift To" content in the right.

<img width="677" alt="screen shot 2016-04-14 at 5 56 17 am" src="https://cloud.githubusercontent.com/assets/2540621/14525131/e058b702-0205-11e6-9907-dbc81e2fc6c0.png">

**Comment by isysd** [comment]
Hey, not bad, but can we change it a little more? The "Destination" field should go on the right. The right side should not say "Shift to" as that is old terminology. The "Address" field is also redundant. Thanks!

**Comment by luisvillara** [comment]
Hi @isysd, I made the change, let me know if this works for you :) thanks!
<img width="737" alt="screen shot 2016-04-15 at 4 13 33 pm" src="https://cloud.githubusercontent.com/assets/2540621/14574397/46d43ba8-0325-11e6-8f56-5dec0563b97e.png">

**Comment by isysd** [comment]
Great! My only concern now is that the "Destination" box is too small... The address that will be put into it is the same size as the Return Address (~35 characters).

**Comment by luisvillara** [comment]
Ok, here is :)
<img width="456" alt="screen shot 2016-04-20 at 11 30 29 pm" src="https://cloud.githubusercontent.com/assets/2540621/14697677/e2b4a4e4-074f-11e6-97f3-eca86bc4492d.png">

**Comment by isysd** [comment]
Looks good, please proceed!
